# Generated by Django 6.0.4 on 2026-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
