# Generated by Django 6.0.5 on 2026-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='manzil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
