# Generated by Django 6.0.5 on 2026-05-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_phone_profile_manzil_profile_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manzil',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefon',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
